// same as above but with enum
export enum MonitorDetailActions {
  ACTION_UPDATE_MONITOR_DETAIL = '$MONITOR_DETAIL_ACTION_UPDATE_MONITOR_DETAIL',
  ACTION_UPDATE_SYNC_STAT = '$MONITOR_DETAIL_ACTION_UPDATE_SYNC_STAT',
  ACTION_UPDATE_STATUS_FETCHING = '$MONITOR_DETAIL_ACTION_UPDATE_STATUS_FETCHING',
  ACTION_UPDATE_COMMITTEE_INFO = '$MONITOR_DETAIL_ACTION_UPDATE_COMMITTEE_INFO',
  ACTION_CLEAR_MONITOR_DETAIL = '$MONITOR_DETAIL_ACTION_CLEAR_MONITOR_DETAIL',
}

export const {
  ACTION_CLEAR_MONITOR_DETAIL,
  ACTION_UPDATE_COMMITTEE_INFO,
  ACTION_UPDATE_MONITOR_DETAIL,
  ACTION_UPDATE_STATUS_FETCHING,
  ACTION_UPDATE_SYNC_STAT,
} = MonitorDetailActions;
