export const ACTION_UPDATE_MONITOR_DETAIL = '$MONITOR_DETAIL_ACTION_UPDATE_MONITOR_DETAIL';
export const ACTION_UPDATE_SYNC_STAT = '$MONITOR_DETAIL_ACTION_UPDATE_SYNC_STAT';
export const ACTION_UPDATE_STATUS_FETCHING = '$MONITOR_DETAIL_ACTION_UPDATE_STATUS_FETCHING';
export const ACTION_UPDATE_COMMITTEE_INFO = '$MONITOR_DETAIL_ACTION_UPDATE_COMMITTEE_INFO';
