import { Column } from 'react-table';

export const MockupData = [
    {
        id: '1',
        name: 'LienMinh1',
        publicKey: '123-123',
        status: 'Waiting',
        committeeChainId: '1',
        syncState: 'Beacon Synced',
        voteStats: '100-90',
    },
    {
        id: '2',
        name: 'LienMinh2',
        publicKey: '456-456',
        status: 'Pending',
        committeeChainId: '2',
        syncState: 'Shard Syncing',
        voteStats: '100-90',
    },
    {
        id: '3',
        name: 'LienMinh3',
        publicKey: '123-123',
        status: 'Waiting',
        committeeChainId: '1',
        syncState: 'Beacon Synced',
        voteStats: '100-90',
    },
    {
        id: '4',
        name: 'LienMinh4',
        publicKey: '456-456',
        status: 'Pending',
        committeeChainId: '2',
        syncState: 'Shard Syncing',
        voteStats: '100-90',
    },
    {
        id: '5',
        name: 'LienMinh5',
        publicKey: '123-123',
        status: 'Waiting',
        committeeChainId: '1',
        syncState: 'Beacon Synced',
        voteStats: '100-90',
    },
    {
        id: '6',
        name: 'LienMinh6',
        publicKey: '456-456',
        status: 'Pending',
        committeeChainId: '2',
        syncState: 'Shard Syncing',
        voteStats: '100-90',
    },
    {
        id: '7',
        name: 'LienMinh7',
        publicKey: '123-123',
        status: 'Waiting',
        committeeChainId: '1',
        syncState: 'Beacon Synced',
        voteStats: '100-90',
    },
    {
        id: '8',
        name: 'LienMinh8',
        publicKey: '456-456',
        status: 'Pending',
        committeeChainId: '2',
        syncState: 'Shard Syncing',
        voteStats: '100-90',
    },
];

export const MockupColumns: any = [
    { accessor: 'name', Header: 'Name' },
    { accessor: 'publicKey', Header: 'Public Key' },
    { accessor: 'committeeChainId', Header: 'Committee ChainId' },
    { accessor: 'status', Header: 'Status' },
    { accessor: 'syncState', Header: 'Sync State' },
    { accessor: 'voteStats', Header: 'Vote Stats' },
];
