export const ACTION_CHANGE_PAGE = '$NODE_MONITOR_ACTION_CHANGE_PAGE';
export const ACTION_CHANGE_LIMIT_ROW_PER_PAGE = '$NODE_MONITOR_ACTION_CHANGE_LIMIT_ROW_PER_PAGE';
export const ACTION_CHANGE_LIMIT_PAGE = '$NODE_MONITOR_ACTION_CHANGE_LIMIT_PAGE';
