export const ACTION_CHANGE_PAGE = '$TABLE_NODE_MONITOR_ACTION_CHANGE_PAGE';
export const ACTION_CHANGE_ROWS_PER_PAGE = '$TABLE_NODE_MONITOR_ACTION_CHANGE_ROWS_PER_PAGE';
export const ACTION_CHANGE_LIMIT_PAGE = '$TABLE_NODE_MONITOR_ACTION_CHANGE_LIMIT_PAGE';
export const ACTION_UPDATE_TABLE_DATA = '$TABLE_NODE_MONITOR_ACTION_UPDATE_TABLE_DATA';
export const ACTION_FETCHING_TABLE_DATA = '$TABLE_NODE_MONITOR_ACTION_FETCHING_TABLE_DATA';
